// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsrhstrfurkgdxjdbhyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzcmhzdHJmdXJrZ2R4amRiaHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDkxMDgsImV4cCI6MjA4Njc4NTEwOH0.aZWMmX_gblPZ1kpCWuNDTfB7oSqf-Te4in1Sh4bjqAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});